### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by uhditya** [uhditya/Codes-for-Cpp#5]
Add a program which can create and implement linked list in C++.

**Comment by Debajyoti111** [comment]
Hey @uhditya , can I work on this issue?

**Comment by Abhijit25Mishra** [comment]
I will provide better code quality. I am expert on codeforces. @uhditya

**Comment by uhditya** [comment]
Ah ok, what's your rating on codeforces?

**Comment by uhditya** [comment]
Alright sure, go ahead. Jyoti you could perhaps work on another issue.

**Comment by aryanayush012** [comment]
I want to contribute. pleaase assign this to me. @Abhijit25Mishra
